apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server-go
  name: server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server-go
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: server-go
    spec:
      containers:
      - args:
        - bash
        - -c
        - go run -mod=vendor main.go
        image: server-go
        imagePullPolicy: ""
        name: server-go
        ports:
        - containerPort: 8690
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
