apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: server-go
  name: server-go
spec:
  ports:
  - name: "8690"
    port: 8690
    targetPort: 8690
  selector:
    io.kompose.service: server-go
status:
  loadBalancer: {}
